package com.solvd.internet_store.enums;

public enum ModelType {
    COSTUMER, DELIVERY_SERVICE, DELIVERY_WORKER, DRIVER, ORDER, PRODUCT, STORAGE,
    USER, VEHICLE, VEHICLE_LICENCE, VEHICLE_SERVICE
}
